![](img/logo.png)

# Numerical Python with NumPy
## Yoav Ram

[NumPy](http://www.numpy.org/) is the fundamental package for scientific computing with Python. It contains arrays, math functions, linear algebra, random number capabilities and much more.

# [![Numpy logo](https://numfocus.org/wp-content/uploads/2016/07/numpy-logo-300.png)](https://matplotlib.org/gallery/mplot3d/voxels_numpy_logo.html)

# Importing NumPy

The convention is `import numpy as np`. This loads the entire NumPy package once, and uses an alias `np` so that we don't pollute our code with too much `numpy`.

Some people like to do `from numpy import *`. This is frowned-upon as it pollutes the namespace: it overrides the default `sum` and hides the fact that we are using specific `numpy` functions.

If you only need specific NumPy objects you can load them using `from numpy import array, ones` etc.

In [1]:
import numpy as np
print("Numpy version:", np.__version__)

Numpy version: 2.0.0


# Analyzing Patient Data

We are studying inflammation in patients who have been given a new treatment for arthritis, and need to analyze the first dozen data sets. The data sets are stored in comma-separated values (CSV) format: each row holds information for a single patient, and the columns represent successive days. The first few rows of our data file look like this:

> 0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0
0,1,2,1,2,1,3,2,2,6,10,11,5,9,4,4,7,16,8,6,18,4,12,5,12,7,11,5,11,3,3,5,4,4,5,5,1,1,0,1
0,1,1,3,3,2,6,2,5,9,5,7,4,5,4,15,5,11,9,10,19,14,12,17,7,12,11,7,4,2,10,5,4,2,2,3,2,2,1,1
0,0,2,0,4,2,2,1,6,7,10,7,9,13,8,8,15,10,10,7,17,4,4,7,6,15,6,4,9,11,3,5,6,3,3,4,2,3,2,1
0,1,1,3,3,1,3,5,2,4,4,7,6,5,3,10,8,10,6,17,9,14,9,7,13,9,12,6,7,7,9,6,3,2,2,4,2,0,1,1


## Loading data from file

We read the file into a NumPy array - the new data structure which is the center of all scientific Python.

In [2]:
fname = "../data/inflammation-01.csv"
data = np.loadtxt(fname, delimiter=',')

The expression `np.loadtxt(...)` is a function call that asks Python to run the function `loadtxt` that belongs to the `numpy` library. This dotted notation is used everywhere in Python to refer to the parts of things as `thing.component` (see: [namespaces](https://stackoverflow.com/a/3913488/1063612)).

`numpy.loadtxt` has two arguments: the name of the file we want to read, and the delimiter that separates values on a line. These arguments need to be strings, so we put them in quotes (either `'` or `"`, it doesn't matter).

We saved the output of `loadtxt` to the variable `data`.
When we `print(data)`, only a few rows and columns are shown (with `...` to omit elements when displaying big arrays).
To save space, Python displays numbers as `1.` instead of `1.0` when there's nothing interesting after the decimal point.

### Other ways to load data from files

- `np.load`: Load arrays or [pickled](https://docs.python.org/3/library/pickle.html?highlight=pickle#module-pickle) objects from pickled files, saved using `np.save` with the extension `.npy` or `.npz` (the latter for gzip compressed files).
- [`np.genfromtxt`](https://docs.scipy.org/doc/numpy-dev/user/basics.io.genfromtxt.html): provides more sophisticated handling of, e.g. lines with missing values.

There are some more special I/O functions in [scipy.io](https://docs.scipy.org/doc/scipy/reference/io.html), for example for reading MATLAB data files and audio files, and [imageio](http://imageio.github.io) for reading image files.

## Manipulating Data

Now that our data is in memory, we can start doing things with it. First, let's ask what type of thing data refers to:

In [3]:
print(type(data))

<class 'numpy.ndarray'>


The output tells us that data currently refers to an N-dimensional array created by the NumPy library. We can see what its shape is like this:

In [4]:
print(data.shape)
n_patients, n_days = data.shape

(60, 40)


This tells us that `data` has 60 rows and 40 columns, which are 60 patients and 40 days. `data.shape` is a member of `data`, i.e. a value that is stored as part of an object.
We use the same dotted notation for the members of objects that we use for the functions in libraries because they have the same part-and-whole relationship.

If we want to get a single value from the matrix, we must provide an index in square brackets, just as we do with a `list`, but with as many indices as the number of dimensions in `shape` (two in this case):

In [5]:
print("first value in data", data[0,0])
print("middle value in data:", data[30, 20])

data[0,0] 

first value in data 0.0
middle value in data: 13.0


np.float64(0.0)

The expression `data[30, 20]` may not surprise you, but `data[0, 0]` might. Programming languages like Fortran and MATLAB start counting at 1, because that's what human beings have done for thousands of years. Languages in the C family (including C++, Java, Perl, and Python) count from 0 because that's simpler for computers to do. Just like with `list` and `str`, if we have an M×N array in Python, its indices go from 0 to M-1 on the first axis and 0 to N-1 on the second. It takes a bit of getting used to, but one way to remember the rule is that the index is how many steps we have to take from the start to get the item we want.

> **In the Corner.**
> What may also surprise you is that when Python displays an array, it shows the element with index [0, 0] in the upper left corner rather than the lower left. This is consistent with the way mathematicians draw matrices, but different from the Cartesian coordinates. The indices are (row, column) instead of (column, row) for the same reason, which can be confusing when plotting data.

An index like `[30, 20]` selects a single element of an array, but we can select whole sections as well. For example, we can select the first ten days (columns) of values for the first four (rows) patients like this:

In [6]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


The slice `0:4` means, "Start at index 0 and go up to, but not including, index 4." Again, the up-to-but-not-including takes a bit of getting used to, but the rule is that the difference between the upper and lower bounds is the number of values in the slice.

We don't have to start slices at 0:

In [7]:
print(data[5:10, 0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


We also don't have to include the upper and lower bound on the slice. If we don't include the lower bound, Python uses 0 by default; if we don't include the upper, the slice runs to the end of the axis, and if we don't include either (i.e. if we just use ':' on its own), the slice includes everything:

In [8]:
small = data[:3, :3].copy()
small[0,0] = 1000
print('small is:')
print(small)

small is:
[[1000.    0.    1.]
 [   0.    1.    2.]
 [   0.    1.    1.]]


## Exercise 1

1. Print the last value of the array, that is, the value at the last row and last column.
1. Print the entire last row.
1. Print the entire last column.

**Tips**
- Edit cell by double clicking
- Run cell by pressing _Shift+Enter_
- Get autocompletion by pressing _Tab_
- Get documentation by pressing _Shift+Tab_

0.0
[ 0.  0.  1.  0.  3.  2.  5.  4.  8.  2.  9.  3.  3. 10. 12.  9. 14. 11.
 13.  8.  6. 18. 11.  9. 13. 11.  8.  5.  5.  2.  8.  5.  3.  5.  4.  1.
  3.  1.  1.  0.]
[0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.
 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1.
 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]


## Operations

We can also perform common arithmetic operations on arrays: add, subtract, multiply, divide, etc.
When you perform these operations on arrays, the operation is done on each individual element of the array, i.e. elementwise.

In [9]:
doubledata = data * 2.0

will create a new array `doubledata` whose elements have the value of two times the value of the corresponding elements in `data`.

In [10]:
print('original:')
print(data[:3, 36:])
print('doubledata:')
print(doubledata[:3, 36:])

original:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]
doubledata:
[[4. 6. 0. 0.]
 [2. 2. 0. 2.]
 [4. 4. 2. 2.]]


This is also much faster than doing it with vanilla Python (`%timeit` is a magic command for measuring running time of single lines; use `%%timeit` to measure time of a whole cell).

The vanilla Python uses a [list comprehension](https://dbader.org/blog/list-dict-set-comprehensions-in-python), which is a very effective way to create lists.

In [11]:
n = 100000
%timeit [x**2 for x in range(n)]
%timeit np.arange(n)**2

5.86 ms ± 153 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
73.6 µs ± 692 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


We can also use binary (i.e. with two arguments) arithmetic operations like addition:

In [11]:
tripledata = doubledata + data

will give you an array where `tripledata[0,0]` will equal `doubledata[0,0]` plus `data[0,0]`, and so on for all other elements of the arrays.

In [12]:
print('tripledata:')
print(tripledata[:3, 36:])

tripledata:
[[6. 9. 0. 0.]
 [3. 3. 0. 3.]
 [6. 6. 3. 3.]]


Just another comparison:

In [32]:
n = 10000
%timeit [x + x**0.5 for x in range(n)]
%timeit x = np.arange(n); x + x**0.5

1.46 ms ± 53 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
259 µs ± 19.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Exercise 2

Calculate the square root of the data using `numpy`. 
Print the result for the first 5 columns of the first 3 rows.

[[0.         0.         1.         1.73205081 1.        ]
 [0.         1.         1.41421356 1.         1.41421356]
 [0.         1.         1.         1.73205081 1.73205081]]


## Descriptive statistics

Often, we want to do more than add, subtract, multiply, and divide values of data. 
We can also do descriptive statistics on arrays.
If we want to find the average inflammation for all patients on all days, for example, we can just calculate the mean vakue of the array.

In [13]:
data.mean()

np.float64(6.14875)

`mean` is a method of the array, i.e. a function that belongs to it in the same way that the member shape does. If variables are nouns, methods are verbs: they describe operations that can be perfomed on the object.
This is why `data.shape` doesn't need to be called (it's a member, not a method) but `data.mean()` does (it's a method).
It is also why we need empty parentheses for `data.mean()`: even when we're not passing in any arguments, parentheses are how we tell Python to call a function (what would happen if you just use `data.mean`?).

NumPy arrays have lots of useful methods:

In [14]:
print('maximum inflammation:', data.max())
print('minimum inflammation:', data.min())
print('standard deviation:', data.std())

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


When analyzing data, though, we often want to look at marginal statistics, such as the maximum value per patient or the average value per day.
One way to do this is to select the data we want to create a new temporary array, then ask it to do the calculation:

In [15]:
patient_0 = data[0, :] # 0 on the first axis, everything on the second
print('maximum inflammation for patient 0:', patient_0.max())

maximum inflammation for patient 0: 18.0


What if we need the maximum inflammation for all patients, or the average for each day? As the diagram below shows, we want to perform the operation across an axis:
![axis example](https://github.com/swcarpentry/python-novice-inflammation/raw/gh-pages/fig/python-operations-across-axes.png)

To support this, most array methods allow us to specify the axis we want to work on.
If we ask for the average across axis 0, we get:

In [16]:
print(data.mean(axis=0))

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]


The expression `(40,)` tells us we have an 1D array of length 40, so this is the average inflammation per day for all patients. If we average across axis 1, we get:

In [17]:
print(data.mean(axis=1))

[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]


which is the average inflammation per patient across all days.

## Exercise 3

On which day did each patient had the most inflammation?
Use `data.argmax` to find out.

[19 20 20 20 19 18 21 20 18 20 19 22 17 19 17 18 21 21 17 21 21 22 18 19
 20 19 22 23 20 18 19 20 15 25 19 23 18 18 20 18 20 20 21 19 21 18 20 15
 24 18 19 20 21 19 18 17 23 19 22 21]


# NumPy reference

We now go through some extra NumPy features worth mentioning.

## Creating arrays

There are [5 general mechanisms for creating arrays](https://docs.scipy.org/doc/numpy-dev/user/basics.creation.html):

1. Conversion from other Python structures (e.g., lists, tuples)
1. Intrinsic numpy array creation objects (e.g., `arange`, `ones`, `zeros`, etc.)
1. Reading arrays from disk, either from standard or custom formats
1. Creating arrays from raw bytes through the use of strings or buffers
1. Use of special library functions (e.g., `numpy.random`)


Let's start by pecifying a list or list of lists to the `np.array` function:

In [18]:
a = np.array([0, 1, 2, 3])
print(a)
type(a), a.dtype

[0 1 2 3]


(numpy.ndarray, dtype('int64'))

The `dtype` attribute gives the data-type. 

We can force a specific data-type:

In [19]:
a = np.uint64([0, 1, 2, 3])
print(a)
type(a), a.dtype

[0 1 2 3]


(numpy.ndarray, dtype('uint64'))

In [20]:
a = np.float16([0, 1, 2, 3])
print(a)
type(a), a.dtype

[0. 1. 2. 3.]


(numpy.ndarray, dtype('float16'))

NumPy has many [data types](https://numpy.org/doc/stable/user/basics.types.html), we'll focus on the default `int` and `float` today.

We can create a 2D array from nested lists - make sure that all nested lists have the same length.

In [21]:
b = np.array(
    [
        [0, 1, 2], 
        [3, 4, 5]
    ]
)
print(b)

[[0 1 2]
 [3 4 5]]


In [22]:
c = np.array(
    [
        [
            [1], 
            [2]
        ], 
        [
            [3], 
            [4]
        ]
    ]
)
print(c)

[[[1]
  [2]]

 [[3]
  [4]]]


Arrays are N-dimensional, so you can specify how many dimensions that you would like:

In [23]:
d = np.array(
    [
        [
            [1, 2],
            [3, 4],
        ],
        [
            [5, 6],
            [7, 8],
        ],        
    ]
)
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Check the number of dimensions and the shape:

In [24]:
print(d.ndim)
print(d.shape)

3
(2, 2, 2)


Use `np.arange`, whish is similar to `range`, but also accepts `float`s:

In [25]:
a = np.arange(10)  # end (exclusive)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
b = np.arange(-1.5, 9.5, 0.2) # start, end (exclusive), step
print(b)

[-1.5 -1.3 -1.1 -0.9 -0.7 -0.5 -0.3 -0.1  0.1  0.3  0.5  0.7  0.9  1.1
  1.3  1.5  1.7  1.9  2.1  2.3  2.5  2.7  2.9  3.1  3.3  3.5  3.7  3.9
  4.1  4.3  4.5  4.7  4.9  5.1  5.3  5.5  5.7  5.9  6.1  6.3  6.5  6.7
  6.9  7.1  7.3  7.5  7.7  7.9  8.1  8.3  8.5  8.7  8.9  9.1  9.3]


`np.linspace` is similar, but it accepts the required number of points rather than the required step.

In [27]:
c = np.linspace(0, 1, 6)   # start, end, num-points
print(c)

[0.  0.2 0.4 0.6 0.8 1. ]


### Exercise: creating arrays

Create an array with the inverse ($1/x$) of the even numbers lower than or equal to 100.

[0.5        0.25       0.16666667 0.125      0.1        0.08333333
 0.07142857 0.0625     0.05555556 0.05       0.04545455 0.04166667
 0.03846154 0.03571429 0.03333333 0.03125    0.02941176 0.02777778
 0.02631579 0.025      0.02380952 0.02272727 0.02173913 0.02083333
 0.02       0.01923077 0.01851852 0.01785714 0.01724138 0.01666667
 0.01612903 0.015625   0.01515152 0.01470588 0.01428571 0.01388889
 0.01351351 0.01315789 0.01282051 0.0125     0.01219512 0.01190476
 0.01162791 0.01136364 0.01111111 0.01086957 0.0106383  0.01041667
 0.01020408 0.01      ]


## Creating arrays - continued
You can can create an empty array of a certain shape (which is given as a `tuple`) or with the same shape as another array; of course, the array will not actually be empty, but rather will have some arbitrary values as it will not be initialized.

You can create an array full of 1s or 0s, or any single number:

In [28]:
a = np.ones((3, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
a = 5.134 * np.ones((3, 3))
print(a)

[[5.134 5.134 5.134]
 [5.134 5.134 5.134]
 [5.134 5.134 5.134]]


In [30]:
b = np.zeros((2, 2))
print(b)

[[0. 0.]
 [0. 0.]]


In [31]:
c = np.zeros_like(b)
print(c)

[[0. 0.]
 [0. 0.]]


In [32]:
d = np.empty((2, 4))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
f = np.empty_like(d)
print(f)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Create the identity matrix:

In [34]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create matrices by specifying the digonals:

In [35]:
d = np.diag([1, 2, 3, 4])
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [36]:
d = np.diag([1, 2, 3], 1) + np.diag([4, 5, 6], -1)
print(d)

[[0 1 0 0]
 [4 0 2 0]
 [0 5 0 3]
 [0 0 6 0]]


Create matrices by reshaping another matrix or array:

In [37]:
f = d.reshape((2, -1))
print(f)

[[0 1 0 0 4 0 2 0]
 [0 5 0 3 0 0 6 0]]


## Random arrays

We'll set the random seed for reproducability (i.e. to get the same result every time), but in real-life application you should think if you want to set the seed.

In [41]:
rng = np.random.default_rng(1231410) 

Start with drawing a single random number uniformly between 0 and 1:

In [42]:
rng.random()

0.30977735983570664

An array of four random numbers between 0 and 1:

In [43]:
a = rng.random(size=4)
print(a)

[0.80969921 0.03667625 0.33983751 0.92332277]


A 3x3 matrix or random numbers drawn from a normal distribution with mean 1 and standard deviation 0.5:

In [44]:
b = rng.normal([0,1,2], 0.5, size=(3, 3))
print(b)

[[0.00653344 0.94398864 2.15873845]
 [0.322567   1.51962986 1.64397642]
 [0.26721274 0.63866911 2.04436038]]


Now draw a 3x2x4 array from a Poisson distribution with mean 5:

In [45]:
c = rng.poisson(5, size=(3, 2, 4))
print(c)

[[[ 3  5  3  7]
  [ 3  5  1  7]]

 [[ 5  4  3  2]
  [ 6  5  6  8]]

 [[11  2  6  6]
  [ 5  7  4  8]]]


### Exercise: random arrays

1) Create a 4x5x6 array with numbers drawn from a geometric distribution with `p=0.1` (the number of trails until success, where the probability of success is `p`).

2) Normalize a 5x5 random matrix - that is, first subsctract by the minimum and then divide by the new maximum.

## Indexing and slicing

Arrays can also be indexed using an array or list of indices, this is called **fancy indexing**.

In [84]:
print(data[[5, 10, 2, 20]])

[[ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.  7.  6.  6.  9.  9. 15.  4. 16.
  18. 12. 12.  5. 18.  9.  5.  3. 10.  3. 12.  7.  8.  4.  7.  3.  5.  4.
   4.  3.  2.  1.]
 [ 0.  1.  0.  0.  4.  3.  3.  5.  5.  4.  5.  8.  7. 10. 13.  3.  7. 13.
  15. 18.  8. 15. 15. 16. 11. 14. 12.  4. 10. 10.  4.  3.  4.  5.  5.  3.
   3.  2.  2.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]
 [ 0.  1.  1.  3.  1.  4.  4.  1.  8.  2.  2.  3. 12. 12. 10. 15. 13.  6.
   5.  5. 18. 19.  9.  6. 11. 12.  7.  6.  3.  6.  3.  2.  4.  3.  1.  5.
   4.  2.  2.  0.]]


Let's use this feature to arrange the rows of the data (patients) by their max value, so that the first row has the lowest max value and the last row has the highest max value.

In [79]:
patient_max = data.max(axis=1)
idx = patient_max.argsort() # index for increasing value
print(idx)

[50 23 32 47 33 53 21 13 39 42 45 30 55 36 48 14 37 54 56 35 52  3  6  4
 22 24 27 25 18 12  8 29 59 58 40 49 44 15 26  0 11 10  1  5  9 17  2 20
 46 43 16 31 19 34 41 38 57  7 28 51]


In [82]:
sorted_data = data[idx]
print(sorted_data.max(axis=1))

[14. 15. 15. 15. 15. 15. 16. 16. 16. 16. 16. 16. 16. 16. 16. 17. 17. 17.
 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 17. 18. 18. 18. 18.
 18. 18. 18. 18. 18. 18. 18. 18. 18. 19. 19. 19. 19. 19. 19. 19. 19. 19.
 19. 19. 19. 20. 20. 20.]


We can also give a list to each axis:

In [85]:
print(data[ [0, 2], [1, 2] ])

[0. 1.]


If one of the indexing lists is smaller than the other, NumPy will attempt broadcasting:

In [86]:
print(data[ [0, 2], [1] ])

[0. 1.]


But broadcasting isn't always possible:

In [87]:
data[[0,2,4], [0,1]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

## Boolean or mask arrays

You can create boolean arrays by using the comparison operators, and then use the boolean arrays to index other arrays. 

Let's find the mean of all values greater than 10:

In [91]:
idx = data > 10
print(idx)
print(data[idx].mean())

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
13.706783369803064


We can also use this for assignment.
Let's say we come to the conclusion that values above 15 are an error and should be 15:

In [95]:
data_clipped = data.copy()
idx = data > 15
data_clipped[idx] = 15

print(data_clipped.max(axis=1))

[15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 14. 15. 15. 15.
 15. 15. 15. 15. 15. 15.]


### Exercise: mask arrays

Given a 1D array, negate (i.e. turn to negative) all elements which are between 3 and 8 (including both), in place (i.e. without creating a new array).

Note 1: you cannot use `and` because it acts on two booleans, whereas we want to do an elementwise "and". This is done using the operator `&`. 

Note 2: `&` is a Python bitwise operator which precedes arithmetic operators.

In [97]:
rng = np.random.default_rng(100)
Z = rng.integers(0, 10, size=20)
print(Z)

[7 8 1 5 0 2 4 0 5 9 9 5 4 7 9 9 0 6 7 1]


In [98]:

print(Z)

[-7 -8  1 -5  0  2 -4  0 -5  9  9 -5 -4 -7  9  9  0 -6 -7  1]


## Broadcasting

A very powerful mechanism of NumPy arrays is [broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).
Broadcasting is used when an operation is used on two arrays of different shapes.
The rules are:

1. If arrays dimension differ, left-pad the smaller array's shape with 1s.
1. If the shapes differ, change any dimension of size 1 to match the dimension of the other array.
1. If shapes still differ, raise an error.

Some exmaples:
![broadcasting examples](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

In [46]:
np.arange(3) + 5

array([5, 6, 7])

In [47]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [48]:
np.arange(3).reshape((3, 1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [49]:
np.ones((3,3)) + np.ones((3,2))

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [50]:
np.ones((3,3,1)) + np.ones((3,1,3))

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

### Exercise: Broadcasting

Given a 1D array `X`, calculate the differences between each two elements of `X` using broadcasting and save it to array `D`, such that
$$
D_{i,j} = X_i - X_j
$$

In [56]:
X = np.linspace(0, 1, 50)

In [58]:
assert D.shape == (X.size, X.size)
assert (D.diagonal() == 0).all()
for i in range(50):
    for j in range(50):
        assert (D[i,j] == X[i] - X[j])

# "Losing Your Loops": Fast Numerical Computing with NumPy 

From the PyCon 2015 conferece, a [presentation](https://speakerdeck.com/jakevdp/losing-your-loops-fast-numerical-computing-with-numpy-pycon-2015) by [Jake VanderPlas](http://vanderplas.com).

Also available on [YouTube](https://www.youtube.com/watch?v=EEUXKG97YRw).

In [21]:
from IPython.display import HTML
HTML('<script async class="speakerdeck-embed" data-id="a5d2540d0d4c452d91f8045ede6ca130" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>')

# Conclusion

We discusses NumPy for fast computing with Python, using four strategies to “lose your loops": universal functions (element-wise operations), aggregators (function that reduce the number of dimensions), broadcasting (resolving operations when shapes are mismatched), and fancy/boolean indexing (using arrays to index arrays).

# References

- [NumPy tutorial](https://github.com/rougier/numpy-tutorial) with some exercises.
- [NumPy for MATLAB users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html)
- [100 NumPy exercise](https://github.com/rougier/numpy-100)

# Colophon
This notebook was written by [Yoav Ram](http://python.yoavram.com).

This work is licensed under a CC BY-NC-SA 4.0 International License.

![Python logo](https://www.python.org/static/community_logos/python-logo.png)